import fs from "fs";
import path from "path";

export function scaffoldNextProject(blueprint: any) {
  const targetDir = path.join(process.cwd(), "output", "app");
  
  fs.mkdirSync(path.join(targetDir, "app"), { recursive: true });
  fs.mkdirSync(path.join(targetDir, "components"), { recursive: true });
  fs.mkdirSync(path.join(targetDir, "public"), { recursive: true });

  const nextConfig = `/** @type {import('next').NextConfig} */
const nextConfig = {
  typescript: { ignoreBuildErrors: true },
  eslint: { ignoreDuringBuilds: true },
};
module.exports = nextConfig;`;
  fs.writeFileSync(path.join(targetDir, "next.config.js"), nextConfig);

  const packageJson = {
    name: blueprint.projectName.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    version: "0.1.0",
    private: true,
    scripts: {
      dev: "next dev -p 3000",
      build: "next build",
      start: "next start -p 3000"
    },
    dependencies: {
      next: "15.1.7",
      react: "^19.0.0",
      "react-dom": "^19.0.0",
      "lucide-react": "^0.475.0",
      clsx: "^2.1.1",
      "tailwind-merge": "^3.0.1"
    },
    devDependencies: {
      typescript: "^5",
      "@types/node": "^20",
      "@types/react": "^19",
      "@types/react-dom": "^19",
      postcss: "^8",
      tailwindcss: "^3.4.1"
    }
  };
  fs.writeFileSync(path.join(targetDir, "package.json"), JSON.stringify(packageJson, null, 2));

  const tailwindConfig = `/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: { extend: {} },
  plugins: [],
};`;
  fs.writeFileSync(path.join(targetDir, "tailwind.config.js"), tailwindConfig);

  const layoutTsx = `import "./globals.css";
export const metadata = {
  title: "${blueprint.projectName}",
  description: "Generated by AI SaaS Factory",
};
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="dark">
      <body className="bg-slate-950 text-slate-100 min-h-screen">{children}</body>
    </html>
  );
}`;
  fs.writeFileSync(path.join(targetDir, "app", "layout.tsx"), layoutTsx);

  const globalsCss = `@tailwind base;
@tailwind components;
@tailwind utilities;`;
  fs.writeFileSync(path.join(targetDir, "app", "globals.css"), globalsCss);
}
